CREATE TABLE [dbo].[Albums]
(
	[Id] INT NOT NULL PRIMARY KEY IDENTITY (1,1),
	[Title] NVARCHAR(100) NOT NULL,
	[Date] DATETIME NOT NULL,
	[UserId] INT NOT NULL, 
    CONSTRAINT [FK_Albums_ToUsers] FOREIGN KEY ([UserId]) REFERENCES [Users](Id)
)
