CREATE TABLE [dbo].[Albums]
(
	[Id] UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWID() ,
	[Title] NVARCHAR(100) NOT NULL,
	[Date] DATETIME NOT NULL,
	[UserId] UNIQUEIDENTIFIER NOT NULL, 
    CONSTRAINT [FK_Albums_ToUsers] FOREIGN KEY ([UserId]) REFERENCES [Users](Id)
)
