CREATE TABLE [dbo].[Contents]
(
	[Id] UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWID(),
	[Title] NVARCHAR(100) NOT NULL,
	[Description] TEXT NOT NULL,
	[LanguageId] UNIQUEIDENTIFIER NOT NULL, 
    CONSTRAINT [FK_Contents_ToLanguage] FOREIGN KEY ([LanguageId]) REFERENCES [Languages]([Id])
)
